In [7]:
import pandas as pd
filename = 'GTI-2023-Overall-scores-2011-2022.xlsx'

df = (
    pd.read_excel(filename, 
                  sheet_name='Overall Scores',
                  header=6,
                 index_col='Country')
)

In [8]:
df

,Iso3c,2012 Rank,2012 Score,2013 Rank,2013 Score,2014 Rank,2014 Score,2015 Rank,2015 Score,2016 Rank,...,2018 Rank,2018 Score,2019 Rank,2019 Score,2020 Rank,2020 Score,2021 Rank,2021 Score,2022 Rank,2022 Score
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,AFG,3,9.134265,3,8.935458,4,8.899861,3,8.864294,3,...,2,9.066529,1,9.039006,1,9.056336,1,9.130089,1,8.822244
Albania,ALB,97,0.826319,99,0.508313,105,0.226891,106,0.000000,106,...,110,0.000000,112,0.000000,105,0.000000,96,0.000000,93,0.000000
Algeria,DZA,14,6.695682,16,6.476254,20,6.129568,26,5.794741,32,...,36,5.113016,39,4.751069,43,4.326213,40,4.426002,37,4.082835
Angola,AGO,72,2.364660,82,1.657740,74,2.016820,90,1.241050,95,...,90,1.319722,96,0.826319,91,0.508313,89,0.290979,90,0.157670
Argentina,ARG,63,2.810899,66,2.581995,75,1.991258,94,1.154499,87,...,60,3.393403,63,3.002530,67,2.429550,57,2.773219,57,2.875466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,VEN,69,2.408456,63,2.649197,80,1.798285,72,2.460256,76,...,34,5.128323,42,4.531190,47,3.989407,46,3.999641,51,3.408650
Vietnam,VNM,112,0.000000,110,0.000000,110,0.000000,106,0.000000,106,...,87,1.520182,93,1.058312,89,0.681852,88,0.406456,89,0.226891
Yemen,YEM,5,8.098513,6,7.983732,6,7.979558,5,8.040715,9,...,13,7.185719,17,6.847371,20,6.158684,21,5.886207,22,5.616402
Zambia,ZMB,112,0.000000,110,0.000000,110,0.000000,106,0.000000,106,...,110,0.000000,112,0.000000,105,0.000000,96,0.000000,93,0.000000
Zimbabwe,ZWE,112,0.000000,110,0.000000,110,0.000000,106,0.000000,106,...,110,0.000000,112,0.000000,105,0.000000,96,0.000000,93,0.000000